# Generated by Django 3.0.6 on 2020-05-23 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.CharField(choices=[('ONLINE_SERVICES', 'ONLINE_SERVICES'), ('RENT', 'RENT'), ('BUSINESS_MISCELLANEOUS', 'BUSINESS_MISCELLANEOUS'), ('TRAVEL', 'TRAVEL'), ('GENERAL_MERCHANDISE', 'GENERAL_MERCHANDISE'), ('RESTUARANTS', 'RESTUARANTS'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('GASOLINE_FUEL', 'GASOLINE_FUEL'), ('INSURANCE', 'INSURANCE'), ('OTHERS', 'OTHERS')], max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
