jobs:
  build:
    working_directory: ~/repo
    docker: # run the steps with Docker
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment: # environment variables for the Postgre container.
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py test
  report-cov:
    docker: # run the steps with Docker
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment: # environment variables for the Postgre container.
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            coverage run --source='authentication/,expenses/' manage.py test && coverage report && coverage html
            coveralls

workflows:
  version: 2
  build_and_report_cov:
    jobs:
      - build
      - report-cov
